### ISSUE TITLE
Exception in stop task 'Ensure systemd services are stopped'

### ISSUE THREAD

**Issue by oscarcarlsson** [devture/com.devture.ansible.role.systemd_service_manager#1]
Hi,

I'm getting an error when running this role in matrix ansible playbook like I'm used to. I can't copy and paste the actual error message either, so just typing what I can see on the console.

> An unhandled exception occurred while templating '{{ devture_systemd_service_manager_services_list }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occured while templating '{{ devture_systemd_service_manager_services_list_auto + devture_systemd_service_manager_services_list_additional }}'. 

Then a long list of the different systemd services involved. Then, finally:

> ): can only concatenate list (not 'generator') to list

I'm probably missing something, this is a quite old setup. I've fetched the latest commits for the major repository.

Any ideas? Or should this have been filed with the parent repo?

**Comment by spantaleev** [comment]
Which version of Ansible is this? What about the Jinja version?

You should probably try upgrading Ansible and/or Jinja.

**Comment by oscarcarlsson** [comment]
```
# ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

I'll try to upgrade.

**Comment by oscarcarlsson** [comment]
Yes, updating to a modern OS did solve this issue. Thank's for the pointer!
